# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table imagen_receta (
  url                           varchar(255),
  id                            bigint
);

create table ingrediente (
  id                            bigint generated by default as identity not null,
  parent_receta_id              bigint,
  nombre                        varchar(255),
  cantidad                      integer,
  unidad                        varchar(255),
  constraint pk_ingrediente primary key (id)
);

create table receta (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  descripcion                   varchar(255),
  pasos                         varchar(255),
  tiempo                        integer,
  constraint pk_receta primary key (id)
);

-- foreign keys and indices
create index ix_ingrediente_parent_receta_id on ingrediente (parent_receta_id);
alter table ingrediente add constraint fk_ingrediente_parent_receta_id foreign key (parent_receta_id) references receta (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table ingrediente drop constraint if exists fk_ingrediente_parent_receta_id;
drop index if exists ix_ingrediente_parent_receta_id;

-- drop all
drop table if exists imagen_receta;

drop table if exists ingrediente;

drop table if exists receta;

