# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table imagen_receta (
  id                            bigint generated by default as identity not null,
  url                           varchar(255),
  constraint pk_imagen_receta primary key (id)
);

create table ingrediente (
  id                            bigint generated by default as identity not null,
  parent_receta_id              bigint,
  nombre_ingrediente            varchar(255),
  cantidad                      integer,
  unidad                        varchar(255),
  constraint pk_ingrediente primary key (id)
);

create table receta (
  id                            bigint generated by default as identity not null,
  nombre                        varchar(255),
  descripcion                   varchar(255),
  pasos                         varchar(255),
  tiempo_en_minutos             integer,
  imagen_id                     bigint,
  constraint uq_receta_imagen_id unique (imagen_id),
  constraint pk_receta primary key (id)
);

-- foreign keys and indices
create index ix_ingrediente_parent_receta_id on ingrediente (parent_receta_id);
alter table ingrediente add constraint fk_ingrediente_parent_receta_id foreign key (parent_receta_id) references receta (id) on delete restrict on update restrict;

alter table receta add constraint fk_receta_imagen_id foreign key (imagen_id) references imagen_receta (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table ingrediente drop constraint if exists fk_ingrediente_parent_receta_id;
drop index if exists ix_ingrediente_parent_receta_id;

alter table receta drop constraint if exists fk_receta_imagen_id;

-- drop all
drop table if exists imagen_receta;

drop table if exists ingrediente;

drop table if exists receta;

