# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table imagen_receta (
  id                            bigint generated by default as identity not null,
  url                           varchar(255),
  constraint pk_imagen_receta primary key (id)
);

create table ingrediente (
  id                            bigint generated by default as identity not null,
  parent_receta_id              bigint,
  nombre_ingrediente            varchar(255),
  cantidad                      integer,
  unidad                        varchar(255),
  constraint pk_ingrediente primary key (id)
);

create table propiedad (
  id                            bigint generated by default as identity not null,
  nombre_propiedad              varchar(255),
  constraint pk_propiedad primary key (id)
);

create table receta (
  id                            bigint generated by default as identity not null,
  nombre                        varchar(255),
  descripcion                   varchar(255),
  pasos                         varchar(255),
  tiempo_en_minutos             integer,
  imagen_id                     bigint,
  constraint uq_receta_imagen_id unique (imagen_id),
  constraint pk_receta primary key (id)
);

create table receta_propiedad (
  receta_id                     bigint not null,
  propiedad_id                  bigint not null,
  constraint pk_receta_propiedad primary key (receta_id,propiedad_id)
);

-- foreign keys and indices
create index ix_ingrediente_parent_receta_id on ingrediente (parent_receta_id);
alter table ingrediente add constraint fk_ingrediente_parent_receta_id foreign key (parent_receta_id) references receta (id) on delete restrict on update restrict;

alter table receta add constraint fk_receta_imagen_id foreign key (imagen_id) references imagen_receta (id) on delete restrict on update restrict;

create index ix_receta_propiedad_receta on receta_propiedad (receta_id);
alter table receta_propiedad add constraint fk_receta_propiedad_receta foreign key (receta_id) references receta (id) on delete restrict on update restrict;

create index ix_receta_propiedad_propiedad on receta_propiedad (propiedad_id);
alter table receta_propiedad add constraint fk_receta_propiedad_propiedad foreign key (propiedad_id) references propiedad (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table ingrediente drop constraint if exists fk_ingrediente_parent_receta_id;
drop index if exists ix_ingrediente_parent_receta_id;

alter table receta drop constraint if exists fk_receta_imagen_id;

alter table receta_propiedad drop constraint if exists fk_receta_propiedad_receta;
drop index if exists ix_receta_propiedad_receta;

alter table receta_propiedad drop constraint if exists fk_receta_propiedad_propiedad;
drop index if exists ix_receta_propiedad_propiedad;

-- drop all
drop table if exists imagen_receta;

drop table if exists ingrediente;

drop table if exists propiedad;

drop table if exists receta;

drop table if exists receta_propiedad;

